# Generated by Django 6.0.3 on 2026-06-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(),
        ),
    ]
